[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
mor_core = "8BwLz8SvdFeT7qqd1nJFQMypTtuuWEpEEpVz6x6DA4Hm"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
claim_rewards = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/claim-rewards.ts"
create_token = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/create-token.ts"
delegate_miner = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/delegate-miner.ts"
delegate_reward_pool = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/delegate-reward-pool.ts"
fetch_miner = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/fetch-miner.ts"
fetch_mining_pool = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/fetch-mining-pool.ts"
initialize_miner = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/initialize-miner.ts"
initialize_pool = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/initialize-pool.ts"
submit_solution_er = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/submit-solution-er.ts"
submit_solution = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/submit-solution.ts"
undelegate_miner = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/undelegate-miner.ts"
undelegate_reward_pool = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/undelegate-reward-pool.ts"
